---
  - name: ensure custom facts directory exists
    file: >
      path={{ ansible_env.HOME }}/.ansible/facts.d
      recurse=yes
      state=directory
  - name: create symlink for boto-config
    file: >
      src="{{ item }}"
      dest="{{ ansible_env.HOME }}/.ansible/facts.d/boto.fact"
      state=link
    with_first_found:
      - "{{ ansible_env.HOME }}/.boto"
      - "{{ ansible_env.HOME }}/.aws/credentials"
  - name: re-read facts after adding custom fact
    setup: >
      filter=ansible_local
      fact_path="{{ ansible_env.HOME }}/.ansible/facts.d"
  - name: reload ansible_local
    setup: filter=ansible_local
