---
galaxy_info:
  author: Hartmut König
  description: managing of DynamoDB
  company: Haufe-Lexware
  min_ansible_version: 1.9
  platforms:
  - name: Debian
    versions:
    - all
  categories:
  - system

dependencies: []
